# -*- coding: utf-8 -*-
"""
Italian -> English identifier maps, one per plugin, for rename_identifiers.py.

Each entry renames a WHOLE identifier token in code spans only (never inside strings/comments).
Targets are chosen to avoid colliding with identifiers already present in the plugin; the renamer
refuses to run if any collision slips through, so grow these maps against its --dry report.

Only genuinely Italian identifiers belong here. JDK/Bukkit/library names and already-English project
names are left out on purpose.
"""

# Identifiers of the four common classes (Help, StaffGuide, ConfigValues, DurationText), applied to
# EVERY plugin at once (rename_identifiers.py --common) so those files stay byte-identical and every
# call site moves with them. One token -> one target, even when the word means slightly different
# things in two classes (e.g. `riga` is a help line and a table row -> both become `row`).
COMMON = {
    # --- public API: StaffGuide fluent builder ---
    "crea": "create",
    "valori": "values",
    "sezione": "section",
    "sottocomandi": "subcommands",
    "comandi": "commands",
    "comandiDettagliati": "detailedCommands",
    "comandoESpiegazione": "commandAndExplanation",
    "permessi": "permissions",
    "impostazioni": "settings",
    "impostazioniDa": "settingsFrom",
    "guasto": "issue",
    "guasti": "issues",
    "mai": "never",
    "scrivi": "write",
    "descriviDefault": "describeDefault",
    "leggiPluginYml": "readPluginYml",
    "leggiSezioniAiuto": "readHelpSections",
    "apriTabella": "openTable",
    "chiudiTabella": "closeTable",
    "tabellaImpostazioni": "settingsTable",
    "chiaveESpiegazione": "keyAndExplanation",
    "valoreLeggibile": "readableValue",
    "sostituisciCoppie": "replacePairs",
    "sost": "substitute",
    "esc": "escapeHtml",
    "aMano": "byHand",
    # --- public API: Help ---
    "mostra": "show",
    "daConfig": "fromConfig",
    "nuovaSezione": "newSection",
    "voce": "entry",
    "voci": "entries",
    "impagina": "paginate",
    "sezioneStampata": "printedSection",
    "titoloSezione": "sectionTitle",
    "pieDiPagina": "footer",
    # --- universal plugin-private method, identical in every plugin's main class ---
    "scriviGuidaStaff": "writeStaffGuide",
    # --- public API: ConfigValues ---
    "applica": "apply",
    # --- public API: DurationText ---
    "finoA": "until",
    "daSecondi": "fromSeconds",
    "daOre": "fromHours",
    "numero": "number",
    # --- generic tokens shared by the common classes (and their call sites) ---
    "nome": "name",
    "testo": "text",
    "valore": "value",
    "chiave": "key",
    "codice": "code",
    "comando": "command",
    "riga": "row",
    "righe": "rows",
    "sezioni": "sections",
    "nota": "note",
    # --- internals: Help ---
    "argomenti": "arguments",
    "avanti": "forward",
    "indietro": "back",
    "corrente": "current",
    "conta": "counter",
    "radice": "root",
    "filo": "rule",
    "pagina": "page",
    "pagine": "pages",
    "pezzi": "pieces",
    "servono": "needed",
    "sinistra": "left",
    "soloStaff": "staffOnly",
    "spiegazione": "explanation",
    "suggerimento": "suggestion",
    "taglio": "cut",
    "titolo": "title",
    "visibili": "visible",
    "intestazione": "header",
    "intestazioni": "headers",
    # --- internals: StaffGuide ---
    "aperto": "opened",
    "apre": "opens",
    "chiude": "closes",
    "celle": "cells",
    "commento": "comment",
    "cosa": "what",
    "cosaFa": "whatItDoes",
    "cosaFare": "whatToDo",
    "documento": "document",
    "etichetta": "label",
    "grezzo": "raw",
    "ordine": "order",
    "paragrafi": "paragraphs",
    "problema": "problem",
    "versione": "version",
    "risalita": "bubbleUp",
    # --- internals: ConfigValues ---
    "atteso": "expected",
    "blocchi": "blocks",
    "corpo": "body",
    "fonti": "sources",
    "forma": "shape",
    "giro": "pass",
    "inoltre": "also",
    "operatore": "operator",
    "rimasto": "leftover",
    "ripiego": "fallback",
    "segno": "sign",
    "tieni": "keep",
    "trovato": "found",
    "uguale": "equal",
    # --- Italian nested types / constants in the common classes ---
    "Voce": "Entry",
    "GRIGIO": "GREY",
    "VIOLA": "PURPLE",
    "VERDE": "GREEN",
    "TENUE": "FAINT",
    "SEPARATORE": "SEPARATOR",
    "PER_PAGINA": "PER_PAGE",
    "BLOCCO": "BLOCK",
    "RIMASTO": "LEFTOVER",
    "SEGNAPOSTO": "PLACEHOLDER",
    "CODICI_COLORE": "COLOR_CODES",
}

MAPS = {
    "MagixAuth": {
        # --- MagixAuth.java (plugin main) ---
        "configurazione": "authConfig",
        "raccogliRevoche": "collectRevocations",
        "scriviGuidaStaff": "writeStaffGuide",
        "ricarica": "reload",

        # --- AuthGate.java: fields ---
        "fermi": "frozen",
        "decisioni": "decisions",
        "cancello": "loginSpawn",
        "biscotto": "cookie",
        "politica": "policy",
        "visibilita": "visibility",
        # --- AuthGate.java: methods / params / locals ---
        "stato": "state",
        "fermo": "isFrozen",
        "decidi": "decide",
        "ricorda": "remember",
        "dirottaSpawn": "hijackSpawn",
        "accogli": "welcome",
        "istruzioni": "instructions",
        "avviaCronometro": "startTimer",
        "provaPassword": "tryPassword",
        "registra": "register",
        "verifica": "checkPassword",
        "provaCodice": "tryCode",
        "riproponi": "reprompt",
        "libera": "release",
        "riportaAlPosto": "sendBackToPlace",
        "pulisciPosizione": "clearPosition",
        "ricongela": "refreeze",
        "abbandona": "abandon",
        "chiudiTutto": "closeAll",
        "ipDi": "ipOf",
        "sulMain": "onMain",
        "leggiCancello": "readLoginSpawn",
        "impostaCancello": "setLoginSpawn",
        "fileCancello": "loginSpawnFile",
        "profilo": "prof",
        "applica": "apply",
        "consegna": "deliver",
        "dispositivoDi": "deviceOf",
        "nuovoGettone": "newCookieToken",
        "senzaTrattini": "withoutDashes",
        "uuidDa": "uuidFrom",
        "uuidAccount": "accountUuid",
        "uuidProposto": "proposedUuid",
        "nome": "name",
        "connessione": "conn",
        "rifiuto": "refusal",
        "bloccato": "blocked",
        "sessioneConOtp": "sessionWithOtp",
        "serveOtp": "needsOtp",
        "serveCodice": "needsCode",
        "dispositivo": "deviceKey",
        "cookieDispositivo": "deviceCookie",
        "gettone": "cookieToken",
        "fase": "phase",
        "posizioneVera": "realPosition",
        "vera": "real",
        "mondo": "targetWorld",
        "dove": "where",
        "fissato": "pinned",
        "scritta": "typed",
        "giusta": "correct",
        "manca": "remaining",
        "segreto": "secret",
        "passo": "step",
        "cifre": "digits",
        "occupato": "busy",
        "scelta": "chosen",
        "annuncia": "announce",
        "motivo": "reason",
        "riga": "row",
        "finale": "finalState",
        "atteso": "expected",

        # --- StatoIngresso.java ---
        "aspettaCodice": "awaitsCode",
        "inRegistrazione": "inRegistration",
        "messaggioIngresso": "savedJoinMessage",
        "taskScadenza": "expiryTask",
        "taskCartello": "signTask",

        # --- AuthConfig.java: config-backed fields ---
        "secondiMassimi": "maxSeconds",
        "tentativiMassimi": "maxAttempts",
        "bloccoMinuti": "lockoutMinutes",
        "passwordMinima": "minPasswordLength",
        "oreSessione": "sessionHours",
        "otpSegueLaSessione": "otpFollowsSession",
        "cookieAttesaMillis": "cookieWaitMillis",
        "trackStaff": "staffTrack",
        "otpFacoltativoPerGiocatori": "otpOptionalForPlayers",
        "passwordPrima": "passwordFirst",
        "controlloRevocheSecondi": "revocationCheckSeconds",
        "spawnAlPostoDellaPosizione": "spawnInsteadOfPosition",
        "invisibileAgliAltri": "hideFromOthers",
        "nascondiGliAltri": "hideOthers",
        "nascondiChat": "hideChat",
        "ritardaMessaggioIngresso": "delayJoinMessage",
        "skinDaMojang": "skinFromMojang",
        "skinMinutiCache": "skinCacheMinutes",
        "annotaUuidPremium": "noteUuidPremium",
        "prefisso": "prefix",
        "dbPorta": "dbPort",
        "dbNome": "dbName",
        "dbUtente": "dbUser",
        "chiaveOtpBase64": "otpKeyBase64",
        "chiaveOtpPronta": "otpKeyReady",

        # --- OtpPolicy.java ---
        "aggiornaGruppi": "refreshGroups",
        "gruppiStaff": "staffGroups",
        "luckPermsPresente": "luckPermsPresent",
        "quantiGruppiStaff": "staffGroupCount",
        "serve": "required",

        # --- Visibilita.java ---
        "nascondi": "hide",
        "separa": "separate",

        # --- AuthDao.java ---
        "perNome": "byName",
        "perUuid": "byUuid",
        "bloccatoFino": "blockedUntil",
        "registraFallimento": "recordFailure",
        "azzeraTentativi": "resetAttempts",
        "salvaSessione": "saveSession",
        "sessione": "session",
        "revocaSessioni": "revokeSessions",
        "dimenticaDispositivo": "forgetDevice",
        "salvaPosizione": "savePosition",
        "leggiPosizione": "readPosition",
        "cancellaPosizione": "deletePosition",
        "potaSessioniScadute": "pruneExpiredSessions",
        "allineaNome": "alignName",
        "cambiaPassword": "changePassword",
        "sbloccaOtp": "unlockOtp",
        "otpFallito": "otpFailed",
        "otpPassoSpeso": "otpStepSpent",
        "indirizziBloccatiDi": "blockedAddressesOf",
        "indirizziBloccatiNoti": "knownBlockedAddresses",
        "registrato": "registered",

        # --- Password.java / OtpCodici.java (crypt) ---
        "impronta": "fingerprint",
        "corrisponde": "matchesHash",
        "perche_no": "whyNot",
        "decifraSegreto": "decryptSecret",
        "chiave": "key",

        # --- MojangLookup.java ---
        "cerca": "lookup",
        "skinDi": "skinOf",
        "ritrovata": "found",
        "fallita": "failed",
        "scalda": "warmUp",

        # --- MauthCommand.java ---
        "aiuto": "help",
        "rispondi": "reply",
        "quantiFermi": "frozenCount",
        "sblocca": "unlock",
        "sessioni": "sessions",

        # --- nested types ---
        "Esito": "Outcome",
        "Fase": "Phase",
        "Biscotto": "Cookie",
        "Visibilita": "Visibility",
        "ConnessioneListener": "ConnectionListener",
        "StatoIngresso": "EntryState",
        "ProfiloSetter": "ProfileSetter",
        "Ritrovata": "Found",
        "Risposta": "Reply",

        # --- remaining private tail (2026-09-01, after the common pass) ---
        "KICK_NOME_OCCUPATO": "KICK_NAME_TAKEN",
        "bersaglio": "target",
        "cambia": "change",
        "chiudi": "close",
        "chiudiSessioniSito": "closeSiteSessions",
        "esito": "outcome",
        "idSito": "siteId",
        "leggi": "read",
        "massimo": "maximum",
        "messaggio": "message",
        "nomeGiocatore": "playerName",
        "nomeMondo": "worldName",
        "normalizza": "normalize",
        "valoreBase64": "base64Value",
        # straggler round
        "OtpCodici": "OtpCodes", "CAMPI": "FIELDS", "CIFRE": "DIGITS", "DENTRO": "INSIDE",
        "PASSO_SECONDI": "STEP_SECONDS", "REGISTRATO": "REGISTERED", "adesso": "now",
        "aggancia": "attach", "altro": "other", "busta": "envelope", "butta": "discard",
        "cartella": "folder", "chiama": "invoke", "chiaveBase64": "keyBase64", "dentro": "inside",
        "entrante": "incoming", "entrato": "entered", "fuori": "outside", "indirizzi": "addresses",
        "inizio": "start", "insieme": "bundle", "kickTroppiTentativi": "kickTooManyAttempts",
        "marchio": "brand", "modulo": "module", "nudo": "bare", "otpBloccato": "otpLocked",
        "passoAdesso": "stepNow", "passoNullo": "nullStep", "piazza": "place", "pulito": "clean",
        "quantoManca": "howMuchLeft", "rompe": "breaks", "tentativo": "attempt",
        "totpBloccatoFino": "totpLockedUntil", "totpTentativi": "totpAttempts",
        "totpUltimoPasso": "totpLastStep", "ultimoPasso": "lastStep",
    },

    "MagixEntities": {
        "nomeProfilo": "profileName",
    },

    "MagixWeb": {
        "Messaggio": "Message",
        "messaggio": "message",
        "messaggi": "messages",
        "esito": "outcome",
        "leggiDaConsegnare": "readToDeliver",
        "salva": "save",
        "inConsegna": "inDelivery",
    },

    "MagixFactions": {
        "aggiungiSeManca": "addIfMissing",
        "applicaDecadimento": "applyDecay",
        "applicaGiroOffline": "applyOfflinePass",
        "caricatoDaNoi": "loadedByUs",
        "copia": "copy",
        "dalSito": "fromSite",
        "punti": "points",
        "soglia": "threshold",
        "tipo": "type",
        "valoriGuide": "guideValues",
        "conSuggerimento": "withSuggestion",
    },

    "MagixGuard": {
        "Categoria": "Category", "Esito": "Outcome", "SITO": "SITE", "Soglia": "Threshold",
        "TESTO": "TEXT",
        "aggiornaStati": "refreshStates", "aggiungi": "add", "ambito": "scope",
        "annullaPerSanzione": "cancelForSanction", "applicaRevocaDalSito": "applyRevokeFromSite",
        "attiva": "activate", "attivo": "active", "automatica": "automaticMode",
        "automatico": "automatic", "avvia": "start", "avviaRilevatori": "startDetectors",
        "avviaSanzioni": "startSanctions", "avvisa": "notify", "avvisaSeServe": "notifyIfNeeded",
        "avvisaStaff": "notifyStaff", "bersaglio": "target", "bersaglioOnline": "targetOnline",
        "cacciaAttiva": "huntActive", "carica": "load", "caricaAllIngresso": "loadOnJoin",
        "categoria": "category", "categorie": "categories", "cerca": "search",
        "cercaDatiPersonali": "searchPersonalData", "cercaInsulti": "searchInsults",
        "cercaPubblicita": "searchAds", "cercaSpam": "searchSpam", "chiSegnala": "whoReports",
        "componiContesto": "buildContext", "contesto": "context",
        "controllaAutomatismo": "checkAutomation", "controllaStaff": "checkStaff",
        "daSito": "fromSite", "descrizione": "description", "dimezzamentoGiorni": "halfLifeDays",
        "durata": "duration", "durataFinale": "finalDuration", "durataLeggibile": "readableDuration",
        "durataMassimaAutomatica": "maxAutomaticDuration", "durataMillis": "durationMillis",
        "durataMinima": "minDuration", "durataSecondi": "durationSeconds", "eraChiuso": "wasClosed",
        "esito": "outcome", "esitoStaff": "staffOutcome", "genera": "generate",
        "generaRegolamento": "generateRules", "grado": "rank", "haDurata": "hasDuration",
        "idSanzione": "sanctionId", "idViolazione": "violationId",
        "introduzioneRegolamento": "rulesIntro", "leggi": "read", "massimo": "maximum",
        "memoria": "memory", "messaggio": "message", "messaggioBan": "banMessage",
        "messaggioKick": "kickMessage", "messaggioMute": "muteMessage", "modo": "mode",
        "motivo": "reason", "motivoProposta": "proposedReason", "nomeDi": "nameOf", "nomi": "names",
        "pausa": "pause", "perGiocatore": "perPlayer", "perPunti": "perPoints", "perTipo": "perType",
        "politica": "policy", "poteri": "powers", "prendiIComandi": "grabCommands",
        "pubblicitaAttiva": "adsActive", "punti": "points", "registro": "log",
        "reportAttivo": "reportActive", "reportMassimoAperti": "reportMaxOpen",
        "reportMotivoMinimo": "reportMinReason", "reportPausaSecondi": "reportCooldownSeconds",
        "revoca": "revoke", "revocaApplicata": "revokeApplied", "revocaUltima": "revokeLast",
        "righeContesto": "contextRows", "rilevatore": "detector", "sanziona": "sanction",
        "sanzioni": "sanctions", "scartoMassimoMs": "maxSkewMs", "scriviRegolamento": "writeRules",
        "segnala": "report", "servizio": "service", "sitoDatabase": "siteDatabase", "sitoDb": "siteDb",
        "sitoHost": "siteHost", "sitoPassword": "sitePassword", "sitoPool": "sitePool",
        "sitoPort": "sitePort", "sitoUser": "siteUser", "soglia": "threshold",
        "sogliaAppenaSuperata": "thresholdJustCrossed", "soglie": "thresholds",
        "spamMassimo": "maxSpam", "storico": "history", "tipo": "type", "togli": "remove",
        "uuidDalNome": "uuidFromName", "violazioni": "violations",
        # straggler round
        "Riga": "Row", "Sessione": "Session", "adesso": "now", "blocchiMinimi": "minBlocks",
        "componiDettaglio": "buildDetail", "componiProve": "buildEvidence", "daDove": "fromWhere",
        "dentroIlTetto": "withinCap", "descrivi": "describe", "dimentica": "forget",
        "inizio": "beginning", "manca": "remaining", "minutiFermo": "frozenMinutes", "nudo": "bare",
        "posizione": "position", "primaRiga": "firstRow", "registraClick": "recordClick",
        "ricordaPosizione": "rememberPosition", "sciogliCodici": "expandCodes", "sessioni": "sessions",
        "sostituisci": "replace",
    },

    "MagixMenus": {
        "AGGIORNA": "REFRESH", "APRI_MENU": "OPEN_MENU", "CHIAVI_DI_SERVIZIO": "SERVICE_KEYS",
        "CHIUDI": "CLOSE", "COMANDO": "COMMAND", "COMANDO_OP": "COMMAND_OP", "DIALOGO": "DIALOG",
        "DURATA_BOTTONI": "BUTTON_DURATION", "EQUAZIONE": "EQUATION", "Esito": "Outcome",
        "GIOCATORI_ONLINE": "ONLINE_PLAYERS", "LISTA": "LIST", "MESSAGGIO": "MESSAGE", "TESTO": "TEXT",
        "TESTO_CONTIENE": "TEXT_CONTAINS", "TESTO_UGUALE": "TEXT_EQUALS", "TOGLI_SOLDI": "TAKE_MONEY",
        "Tipo": "Type", "TipoCampo": "FieldType", "aggiorna": "refresh", "aggiornaClient": "refreshClient",
        "aggiornaVariabili": "refreshVariables", "aggiungi": "add", "apertoDi": "openedBy",
        "apri": "open", "apriMenu": "openMenu", "apriPerNome": "openByName", "apriSe": "openIf",
        "attesaFraClic": "clickDelay", "avviaAggiornamento": "startRefresh", "azione": "action",
        "azioni": "actions", "azioniApertura": "openActions", "azioniChiusura": "closeActions",
        "azioniGrezze": "rawActions", "azioniNegate": "deniedActions", "azioniPer": "actionsFor",
        "calcolaCaselleVive": "computeLiveSlots", "carica": "load", "casella": "slot",
        "casellaViva": "liveSlot", "caselle": "slots", "chiaveAzioni": "actionsKey",
        "chiaveAzioniIt": "actionsKeyIt", "chiaveAzioniItaliana": "actionsKeyItalian",
        "chiaveRequisiti": "requirementsKey", "chiaveRequisitiItaliana": "requirementsKeyItalian",
        "chiudi": "close", "chiudiTutti": "closeAll", "clic": "click", "clicSe": "clickIf",
        "colore": "color", "conCaselle": "withSlots", "contenuto": "content", "contesto": "context",
        "contestoCon": "contextWith", "copia": "copy", "copiaEsempio": "copyExample",
        "descrizione": "description", "dialoghi": "dialogs", "dialogo": "dialog", "disegna": "draw",
        "duePunti": "colon", "elencoDiTesti": "textList", "esito": "outcome", "ferma": "stop",
        "gestore": "manager", "giocatore": "player", "haRequisitiDiClic": "hasClickRequirements",
        "leggi": "read", "leggiColore": "readColor", "lista": "list", "massimo": "maximum",
        "messaggi": "messages", "messaggio": "message", "mettiInPausa": "pauseUpdates",
        "minimo": "minimum", "mostraSe": "showIf", "nascondiDettagli": "hideDetails",
        "nomeEArgomenti": "nameAndArgs", "nomeFile": "fileName", "nomeMateriale": "materialName",
        "nomeMerce": "productName", "nomeTipo": "typeName", "nomeVisibile": "displayName",
        "nomi": "names", "pausa": "paused", "registraComandi": "registerCommands",
        "requisiti": "requirements", "requisitiClic": "clickRequirements", "requisito": "requirement",
        "ricaricaTutto": "reloadAll", "segnaClic": "markClick", "sezioneContenuto": "contentSection",
        "sottoAzioni": "subActions", "suClic": "onClick", "testi": "texts", "testoCon": "textWith",
        "tipo": "type", "tipoCampo": "fieldType", "tipoScritto": "writtenType", "togli": "remove",
        "togliBarra": "removeBar", "ultimoClic": "lastClick",
        "valoriPerLaDescrizione": "valuesForDescription",
        # straggler round
        "Campo": "Field", "INDIETRO": "BACK", "MONDO": "WORLD", "OPERATORE": "OPERATOR",
        "PAGINA": "PAGE", "SCELTA": "CHOICE", "TITOLO": "TITLE", "altro": "other",
        "calcolaSeDinamico": "computeIfDynamic", "campi": "fields", "campiDi": "fieldsOf",
        "campo": "field", "cartella": "folder", "chiavi": "keys", "chiusuraLibera": "freeClose",
        "conCampi": "withFields", "dentro": "inside", "dimentica": "forget", "dove": "where",
        "grezzoBottoni": "rawButtons", "mondo": "world", "pagineTotali": "totalPages", "passo": "step",
        "perPagina": "perPage", "piuRighe": "multiLine", "primaSezione": "firstSection",
        "pulito": "clean", "quanteServono": "howManyNeeded", "registraPlaceholder": "registerPlaceholder",
        "righeSuMisura": "customRows", "sezioneCampi": "fieldsSection", "sezioneFinta": "fakeSection",
        "sezioneItem": "itemSection", "sezioneVoce": "entrySection", "tipiDisponibili": "availableTypes",
        "titoloVivo": "liveTitle", "trova": "find", "vera": "real", "vero": "trueValue",
        "visibile": "visible",
    },
}
